### PR TITLE
Upgrade unit-threaded from v0.10.8 to v1.0.11

### PR DESCRIPTION
**Pull request by Geod24**
[...]

~For reference, just did the same here: https://github.com/dlang-community/std_data_json/pull/50~
Can I also get a tag after this is merged ? For Buildkite.

### CODE REVIEW

**Comment by atilaneves** [comment]
I've never understood the reasoning behind not checking in the exact versions for libraries. How else would I get reproducible CI for it?

**Comment by Geod24** [comment]
While I'm not the one to that made this recommendation, I assume it was made under the assumption that reproducible was less of a concern if you could rely on SemVer.
But perhaps I should page @s-ludwig here. Do you prefer to have this change to an upgrade of dependency @atilaneves ?

**Comment by atilaneves** [comment]
What is this PR trying to accomplish?

**Comment by Geod24** [comment]
Upgrading the `unit-threaded` dependency so it picks up the fixes I made.

**Comment by atilaneves** [comment]
Then why wouldn't you `dub upgrade` instead?

**Comment by Geod24** [comment]
I mentioned it in the OP.

**Comment by atilaneves** [comment]
In the link? I just clicked it and still don't know why anyone recommends not checking in the versions used in the library itself, or why `dub upgrade` isn't the way forward.

**Comment by Geod24** [comment]
I have no strong feeling either way, simply trying to be consistent. Changed it to a `dub upgrade`.

**Pull request merged**
